title: Swan-Technical
email: 
description: >-
  Real-world enablement workflows for Microsoft data and AI and end-to-end automation
baseurl: ""
url: "https://mikeswantek.com"
permalink: /:year/:month/:day/:title/
timezone: America/Detroit
markdown: kramdown

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: Mike Swantek
